telegram.bot.token=ВАШ_ТОКЕН (вписать)
admin.secret.command.cleanNeo4j=СБРОС_ВСЕЙ_ВСЕЙ _ИСТОРИИ_БОТА (вписать)



spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USER}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
spring.data.neo4j.database=${NEO4J_DATABASE:neo4j}

logging.pattern.console=%-5level %msg%n


logging.level.org.springframework.data.neo4j=ERROR
logging.level.org.neo4j.driver=ERROR
logging.level.org.telegram.telegrambots=OFF


spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.messages.cache-duration=1s
